### ISSUE TITLE
implement remaining features

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#10]
Here's a list of remaining work, provided by @andrealin:

- [x] “Hide Curves" checkbox for all graph controls
- [x] Equations for each line on the graph -- moved to #21
- [x] "NO REAL ROOTS” text on _Integers_ scene of _Standard Form_ screen, when appropriate
- [x] Control panel icons
- [x] Sliders: snap to zero
- [x] Sliders: non-linear response
- [x] TODOs in the code
- [ ] ❌Draggable point connected to the focus and the directrix on _Vertex Form_ screen
- [x] Math for the point tool doesn’t work for all quadratics. An example is -1 < a < 1 -- move to #22
- [x] Internationalization (stringTest, maxWidth, etc.)
- [x] Implement disposal
- [x] implementation-notes.md - see #9
- [x] model.md - see #8

**Comment by pixelzoom** [comment]
Baseline dev version, prior to making any changes:
https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.3/phet/graphing-quadratics_en_phet.html

**Comment by pixelzoom** [comment]
All items in this issue have been either addressed, or broken out into separate issues.  Closing.
