### ISSUE TITLE
Graphing Quadratics - master checklist

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#3]
## Design
- [x] **Sim folder and design doc created** (Date: //)
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [ ] **Sim suggestions doc reviewed**
- [x] **Learning goals and standards identified** (Date: 2014)
- [x] **Design concept complete**  (Date: 2014)
- [x] **Wireframes complete** (Date: 2014)
- [x] **Mockups complete** (Date: 9/17/18)
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion**
- [x] **Interviews complete** (Date: 10/12/18)
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: //)
  - [x] Performance acceptable, see #48
  - [x] Carefully review ?showPointerAreas, see #19
  - [x] No new feature requests
- [ ] **Pre-publication items**
  - [x] Auxilary screenshots (up to 3 additional), see #111
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Sim primer draft
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [x] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [x] **Post-publication items**
  - [x] Add to Edmodo
  - [x] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [x] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [x] Sim primer (create issue, publish ideally within 1 month of live sim)

## Implementation
- [x] **Repository created** (Date: 6/3/14)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] Use `grunt create-sim` in perennial (see `--help` for arguments) to create the repository structure
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [x] **Development started** (Date: 7/10/18)
- [x] **Sim is "feature complete"** (Date: 10/3/18)
- [x] **Code review completed** (Date: 11/6/18)
- [x] **Pre-publication items**
  - [x] Main screenshot, see #111
  - [x] Verify credits, see #4
- [x] **Published** (Date: 12/7/18)
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [x] **Dev testing started** (Date: 10/18/18)
- [x] **Dev testing completed** (Date: ?)
- [x] **First RC published** (Date: 11/20/18)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 12/6/18)

**Comment by pixelzoom** [comment]
The sim is entering RC testing, time for @amanda-phet to catch up on checklist items, and complete the "pre-publication" items.

**Comment by pixelzoom** [comment]
@KatieWoe please completed this checklist item:

> - [ ] Test matrices put in Testing Matrices Folder

**Comment by pixelzoom** [comment]
@ariel-phet please add to Edmodo, Gooru, etc.

**Comment by ariel-phet** [comment]
@amanda-phet remaining items are for you to check off (I think most of them were done when you published)

Feel free to close after making separate issues for the primer and a deferred issue like https://github.com/phetsims/equality-explorer-two-variables/issues/5 for the LoL items

**Comment by pixelzoom** [comment]
@amanda-phet since Graphing Lines and Graphing Slope-Intercept are marked for LoL delivery (see https://github.com/phetsims/graphing-lines/issues/126), it would be nice to have this sim included too.

**Comment by amanda-phet** [comment]
Yes, this sim is included! I have 24 screens that I am prepping for LoL right now.

**Comment by pixelzoom** [comment]
@amanda-phet update? Should we create a LoL issue so that we can close this issue?  Anything else in the checklist that needs an issue, like Sim Primer?

**Comment by amanda-phet** [comment]
Delivered to LoL 3/13/19. This can be closed.
